[package]
name = "pede"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.3"
bevy_egui = "0.33.0"
bevy_panorbit_camera = "0.23.0"
rand = "0.9.0"  
once_cell = "1.20.3"
serde = { version = "1.0.218", features = ["derive"] }
toml = "0.8.20"

[profile.dev.package."*"]
opt-level = 3