[package]
name = "pede"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
bevy_egui = "0.32.0"
bevy_panorbit_camera = "0.21.1"
rand = "0.8.4"  
#gstreamer = { version = "0.23.4", features = ["v1_18"] }

[profile.dev.package."*"]
opt-level = 3