[package]
name = "pede"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.2"
bevy_egui = "0.32.0"
bevy_panorbit_camera = "0.22.1"
rand = "0.9.0"  
once_cell = "1.20.3"

[profile.dev.package."*"]
opt-level = 3